//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Curd_Operations.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student_Details
    {
        public int Std_ID { get; set; }
        [Required(ErrorMessage ="Required")]
        public string Std_FName { get; set; }
        [Required(ErrorMessage = "Required")]
        public string Std_LName { get; set; }
        [Required(ErrorMessage = "Required")]
        public string Std_Cnic { get; set; }
        public System.DateTime Std_Dob { get; set; }
        [Required(ErrorMessage = "Required")]
        [EmailAddress]
        public string Std_Email { get; set; }
        [Required(ErrorMessage = "Required")]
        [MinLength(11,ErrorMessage ="Phone No Should Be 11 Digit")]
        public string Std_PhoneNo { get; set; }
        public string Std_Gender { get; set; }
        public string Std_Address { get; set; }
        public string Std_Grade { get; set; }
    }
   
}
